# Generated by Django 5.2.3 on 2025-06-27 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Gambar')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Pembelian')),
            ],
            options={
                'verbose_name': 'Pembelian Stok',
                'verbose_name_plural': 'Pembelian Stok',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Supplier')),
                ('contact', models.CharField(max_length=50, verbose_name='Kontak')),
                ('address', models.TextField(verbose_name='Alamat')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, verbose_name='ID Pegawai')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pegawai')),
            ],
            options={
                'verbose_name': 'Kasir',
                'verbose_name_plural': 'Kasir',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Nomor Telepon')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Pelanggan',
                'verbose_name_plural': 'Pelanggan',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Transaksi')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pajak')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diskon')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Bayar')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Sudah Dibayar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Toko.cashier', verbose_name='Kasir')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toko.customer', verbose_name='Pelanggan')),
            ],
            options={
                'verbose_name': 'Pesanan',
                'verbose_name_plural': 'Pesanan',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Tunai'), ('card', 'Kartu'), ('qris', 'QRIS'), ('transfer', 'Transfer Bank')], max_length=50, verbose_name='Metode Pembayaran')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Pembayaran')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Toko.order', verbose_name='Pesanan')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Produk')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga Jual')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Harga Modal')),
                ('stock', models.PositiveIntegerField(verbose_name='Stok')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Gambar Produk')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Toko.category', verbose_name='Kategori')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Toko.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Jumlah')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga Satuan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Toko.order', verbose_name='Pesanan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toko.product', verbose_name='Produk')),
            ],
            options={
                'verbose_name': 'Item Pesanan',
                'verbose_name_plural': 'Item Pesanan',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Jumlah')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga Beli')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toko.product', verbose_name='Produk')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Toko.purchase', verbose_name='Pembelian')),
            ],
            options={
                'verbose_name': 'Item Pembelian',
                'verbose_name_plural': 'Item Pembelian',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Alasan Retur')),
                ('return_date', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Retur')),
                ('quantity', models.PositiveIntegerField(verbose_name='Jumlah Retur')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toko.orderitem', verbose_name='Item Pesanan')),
            ],
            options={
                'verbose_name': 'Retur',
                'verbose_name_plural': 'Retur',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toko.supplier', verbose_name='Supplier'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('kasir', 'Kasir')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
