# Generated by Django 5.2.4 on 2025-07-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode'),
        ),
    ]
